const bitcoin = {
  articles: [
    {
      date: '2023-02-20 02:32:54',
      keywords: [
        'co-founder Cameron Winklevoss',
        'Gemini co-founder Cameron',
        'Cameron Winklevoss',
        'crypto bull run',
        'co-founder Cameron',
        'Gemini co-founder',
        'embrace crypto',
        'bull run',
        'crypto bull',
        'Asia',
      ],
      sentiment: {
        class: 'negative',
        polarity: -0.13,
        subjectivity: 0.23,
      },
      source: 'CoinTelegraph',
      subject: 'bitcoin',
      text: 'Gemini co-founder Cameron Winklevoss believes the next crypto bull run will come from Asia, while America has two options — embrace crypto or be left behind.',
      title:
        'Crypto’s next bull run will come from the East: Gemini co-founder',
      url: 'https://cointelegraph.com/news/crypto-s-next-bull-run-will-come-from-the-east-gemini-co-founder',
      avatar: 'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
    },
    {
      date: '2023-02-20 01:08:44',
      keywords: [
        'BTC market cap',
        'FTX shaved',
        'collapse of FTX',
        'days last year',
        'BTC market',
        'market cap',
        'managed to fully',
        'fully recover',
        'recover and stack',
        'BTC has managed',
      ],
      sentiment: {
        class: 'neutral',
        polarity: 0,
        subjectivity: 0.07,
      },
      source: 'CoinTelegraph',
      subject: 'bitcoin',
      text: "While the collapse of FTX shaved $100 billion off of BTC's market cap in just four days last year, BTC has managed to fully recover and stack on another $65 billion.",
      title: "Bitcoin market cap 'flips' payments giant Visa for the 3rd time",
      url: 'https://cointelegraph.com/news/bitcoin-market-cap-flips-payments-giant-visa-for-the-3rd-time',
      avatar: 'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
    },
    {
      date: '2023-02-19 21:45:07',
      keywords: [
        'VET and RPL',
        'BTC ’s shallow',
        'buying in FIL',
        'OKB',
        'level could lead',
        'BTC',
        'FIL',
        'VET',
        'RPL',
        'shallow correction',
      ],
      sentiment: {
        class: 'negative',
        polarity: -0.12,
        subjectivity: 0.45,
      },
      source: 'CoinTelegraph',
      subject: 'bitcoin',
      text: 'BTC’s shallow correction near the $25,000 level could lead to dip buying in FIL, OKB, VET and RPL.',
      title:
        'Bitcoin’s bullish price action continues to bolster rallies in FIL, OKB, VET and RPL',
      url: 'https://cointelegraph.com/news/bitcoin-s-bullish-price-action-continues-to-bolster-rallies-in-fil-okb-vet-and-rpl',
      avatar: 'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
    },
    {
      date: '2023-02-19 19:35:00',
      keywords: [
        'crypto scam revenue',
        'drop in crypto',
        'crypto scam',
        'scam revenue',
        'revenue was due',
        'due to market',
        'market conditions',
        'low price',
        'price of bitcoin',
        'assets.',
      ],
      sentiment: {
        class: 'negative',
        polarity: -0.08,
        subjectivity: 0.35,
      },
      source: 'CryptoPotato',
      subject: 'bitcoin',
      text: 'The drop in crypto scam revenue was due to market conditions and the low price of bitcoin and other assets.\\xa0',
      title: 'Crypto Scam Revenue Plunged by 46% in 2022: Report',
      url: 'https://cryptopotato.com/crypto-scam-revenue-plunged-by-46-in-2022-report/',
      avatar: 'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
    },
    {
      date: '2023-02-19 16:50:57',
      keywords: [
        'Bitcoin exchange traders',
        'large-volume Bitcoin exchange',
        'fresh burst higher',
        'close for BTC',
        'BTC price',
        'large-volume Bitcoin',
        'Bitcoin exchange',
        'exchange traders',
        'fresh burst',
        'burst higher',
      ],
      sentiment: {
        class: 'positive',
        polarity: 0.28,
        subjectivity: 0.5,
      },
      source: 'CoinTelegraph',
      subject: 'bitcoin',
      text: 'A fresh burst higher into the weekly close for BTC price comes in tandem with suspicions over the motives of large-volume Bitcoin exchange traders.',
      title:
        "Bitcoin continues to 'mirror' 2017 as weekend sees third attack on $25K",
      url: 'https://cointelegraph.com/news/bitcoin-continues-to-mirror-2017-as-weekend-sees-third-attack-on-25k',
      avatar: 'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
    },
    {
      date: '2023-02-18 23:23:00',
      keywords: [
        'digital asset payments',
        'embrace digital asset',
        'Bahrain Al Dana',
        'Dana Resort',
        'Novotel Bahrain',
        'Resort will supposedly',
        'Kingdom to embrace',
        'asset payments',
        'embrace digital',
        'digital asset',
      ],
      sentiment: {
        class: 'positive',
        polarity: 0.12,
        subjectivity: 0.17,
      },
      source: 'CryptoPotato',
      subject: 'bitcoin',
      text: 'Novotel Bahrain Al Dana Resort will supposedly become the first hotel in the Kingdom to embrace digital asset payments.',
      title:
        'Arab World Crypto Adoption: Leading Bahrainian Hotel Accepts BTC Payments (Report)',
      url: 'https://cryptopotato.com/arab-world-crypto-adoption-leading-bahrainian-hotel-accepts-btc-payments-report/',
      avatar: 'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
    },
    {
      date: '2023-02-18 17:00:13',
      keywords: [
        'proponent Udi Wertheimer',
        'Ordinals proponent Udi',
        'Udi Wertheimer',
        'Bitcoin NFTs',
        'proponent Udi',
        'Bitcoin network',
        'Ordinals proponent',
        'increasing popularity',
        'impact posively',
        'posively the security',
      ],
      sentiment: {
        class: 'neutral',
        polarity: 0,
        subjectivity: 0,
      },
      source: 'CoinTelegraph',
      subject: 'bitcoin',
      text: 'The increasing popularity of Bitcoin NFTs, or Ordinals, will impact posively the security of the Bitcoin network and attract developers to the ecosystem, according to Ordinals proponent Udi Wertheimer.',
      title: 'How the Ordinals movement will benefit the Bitcoin blockchain',
      url: 'https://cointelegraph.com/news/how-the-ordinals-movement-will-benefit-the-bitcoin-blockchain',
      avatar: 'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
    },
    {
      date: '2023-02-18 14:00:05',
      keywords: [
        'rapidly evolving industry',
        'Explore the economics',
        'evolving industry',
        'economics of cryptocurrency',
        'cryptocurrency mining',
        'challenges and opportunities',
        'opportunities that exist',
        'rapidly evolving',
        'Explore',
        'industry',
      ],
      sentiment: {
        class: 'neutral',
        polarity: 0,
        subjectivity: 0,
      },
      source: 'CoinTelegraph',
      subject: 'bitcoin',
      text: 'Explore the economics of cryptocurrency mining and the challenges and opportunities that exist in this rapidly evolving industry.',
      title:
        'The economics of cryptocurrency mining: Costs, revenues and market trends',
      url: 'https://cointelegraph.com/news/the-economics-of-cryptocurrency-mining-costs-revenues-and-market-trends',
      avatar: 'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
    },
    {
      date: '2023-02-18 10:36:58',
      keywords: [
        'Bitcoin monthly RSI',
        'BTC bulls battle',
        'bulls battle multiple',
        'battle multiple long-term',
        'multiple long-term resistance',
        'long-term resistance trend',
        'resistance trend lines',
        'monthly RSI',
        'hope as BTC',
        'BTC bulls',
      ],
      sentiment: {
        class: 'neutral',
        polarity: 0,
        subjectivity: 0,
      },
      source: 'CoinTelegraph',
      subject: 'bitcoin',
      text: 'Bitcoin monthly RSI provides a window of hope as BTC bulls battle multiple long-term resistance trend lines at once in February.',
      title:
        'Bitcoin faces do-or-die weekly, monthly close with macro bull trend at stake',
      url: 'https://cointelegraph.com/news/bitcoin-faces-do-or-die-weekly-monthly-close-with-macro-bull-trend-at-stake',
      avatar: 'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
    },
  ],
};

const ethereum = {
  articles: [
    {
      avatar: 'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
      date: '2023-02-19 14:01:08',
      keywords: [
        'Monetizing digital art',
        'Monetizing digital',
        'proof of ownership',
        'potential for royalties',
        'digital art',
        'art with NFTs',
        'NFTs provides proof',
        'Monetizing',
        'ownership',
        'increased',
      ],
      sentiment: {
        class: 'neutral',
        polarity: 0,
        subjectivity: 0.5,
      },
      source: 'CoinTelegraph',
      subject: 'ethereum',
      text: 'Monetizing digital art with NFTs provides proof of ownership, increased value and potential for royalties.',
      title: '5 ways to monetize your digital art with NFTs',
      url: 'https://cointelegraph.com/news/5-ways-to-monetize-your-digital-art-with-nfts',
      avatar: 'https://cdn.coinranking.com/rk4RKHOuW/eth.svg',
    },
    {
      date: '2023-02-18 12:42:00',
      keywords: [
        'Paul Pierce',
        'Ethereum Max',
        'promotion of Ethereum',
        'NBA',
        'Paul',
        'Max',
        'Pierce',
        'SEC',
        'Ethereum',
        'charged',
      ],
      sentiment: {
        class: 'negative',
        polarity: -0.1,
        subjectivity: 0.6,
      },
      source: 'CryptoPotato',
      subject: 'ethereum',
      text: 'NBA Hall-of-Famer Paul Pierce has been charged by the SEC for being involved in the promotion of Ethereum Max.',
      title:
        'SEC Charges NBA Hall of Famer Paul Pierce for Promoting Ethereum Max',
      url: 'https://cryptopotato.com/sec-charges-nba-hall-of-famer-paul-pierce-for-promoting-ethereum-max/',
      avatar: 'https://cdn.coinranking.com/rk4RKHOuW/eth.svg',
    },
    {
      date: '2023-02-18 12:42:00',
      keywords: [
        'Paul Pierce',
        'Ethereum Max',
        'promotion of Ethereum',
        'NBA',
        'Paul',
        'Max',
        'Pierce',
        'SEC',
        'Ethereum',
        'charged',
      ],
      sentiment: {
        class: 'negative',
        polarity: -0.1,
        subjectivity: 0.6,
      },
      source: 'CryptoPotato',
      subject: 'ethereum',
      text: 'Hall-of-Famer Paul Pierce has been charged by the SEC for being involved in the promotion of Ethereum Max.',
      title:
        'Promoting Ethereum Max: Charges NBA Hall of Famer Paul Pierce for ',
      url: 'https://cryptopotato.com/sec-charges-nba-hall-of-famer-paul-pierce-for-promoting-ethereum-max/',
      avatar: 'https://cdn.coinranking.com/rk4RKHOuW/eth.svg',
    },
    {
      date: '2023-02-18 12:42:00',
      keywords: [
        'Paul Pierce',
        'Ethereum Max',
        'promotion of Ethereum',
        'NBA',
        'Paul',
        'Max',
        'Pierce',
        'SEC',
        'Ethereum',
        'charged',
      ],
      sentiment: {
        class: 'negative',
        polarity: -0.1,
        subjectivity: 0.6,
      },
      source: 'CryptoPotato',
      subject: 'ethereum',
      text: 'Paul Pierce has been charged by the SEC for being involved in the promotion of Ethereum Max NBA Hall-of-Famer .',
      title:
        'NBA Hall of Famer Paul Pierce for Promoting Ethereum Max SEC Charges ',
      url: 'https://cryptopotato.com/sec-charges-nba-hall-of-famer-paul-pierce-for-promoting-ethereum-max/',
      avatar: 'https://cdn.coinranking.com/rk4RKHOuW/eth.svg',
    },
    {
      date: '2023-02-18 12:42:00',
      keywords: [
        'Paul Pierce',
        'Ethereum Max',
        'promotion of Ethereum',
        'NBA',
        'Paul',
        'Max',
        'Pierce',
        'SEC',
        'Ethereum',
        'charged',
      ],
      sentiment: {
        class: 'negative',
        polarity: -0.1,
        subjectivity: 0.6,
      },
      source: 'CryptoPotato',
      subject: 'ethereum',
      text: 'Hall-of-Famer Paul Pierce has been charged by the SEC for being involved in the promotion of Ethereum Max.',
      title:
        'Famer Paul Pierce for Promoting Ethereum Max SEC Charges NBA Hall',
      url: 'https://cryptopotato.com/sec-charges-nba-hall-of-famer-paul-pierce-for-promoting-ethereum-max/',
      avatar: 'https://cdn.coinranking.com/rk4RKHOuW/eth.svg',
    },
    {
      date: '2023-02-18 12:42:00',
      keywords: [
        'Paul Pierce',
        'Ethereum Max',
        'promotion of Ethereum',
        'NBA',
        'Paul',
        'Max',
        'Pierce',
        'SEC',
        'Ethereum',
        'charged',
      ],
      sentiment: {
        class: 'negative',
        polarity: -0.1,
        subjectivity: 0.6,
      },
      source: 'CryptoPotato',
      subject: 'ethereum',
      text: 'Paul Pierce has been charged by the SEC for being involved in the promotion of Ethereum Max NBA Hall-of-Famer.',
      title: 'Hall of Famer Paul Pierce for Promoting Ethereum Max',
      url: 'https://cryptopotato.com/sec-charges-nba-hall-of-famer-paul-pierce-for-promoting-ethereum-max/',
      avatar: 'https://cdn.coinranking.com/rk4RKHOuW/eth.svg',
    },
  ],
};

const tetherUSD = {
  articles: [
    {
      date: '2023-02-19 14:01:08',
      keywords: [
        'Monetizing digital art',
        'Monetizing digital',
        'proof of ownership',
        'potential for royalties',
        'digital art',
        'art with NFTs',
        'NFTs provides proof',
        'Monetizing',
        'ownership',
        'increased',
      ],
      sentiment: {
        class: 'neutral',
        polarity: 0,
        subjectivity: 0.5,
      },
      source: 'CoinTelegraph',
      subject: 'Tether USD',
      text: 'Tether belongs to a fast-growing breed of cryptocurrencies called stablecoins, which aim to keep the price of their tokens stable, most commonly by tying it to the price of a traditional currency like the U.S. dollar.',
      title: 'Is Tether a Stablecoin?',
      url: 'https://cointelegraph.com/news/5-ways-to-monetize-your-digital-art-with-nfts',
      avatar: 'https://cdn.coinranking.com/mgHqwlCLj/usdt.svg',
    },
    {
      date: '2023-02-18 12:42:00',
      keywords: [
        'Paul Pierce',
        'Ethereum Max',
        'promotion of Ethereum',
        'NBA',
        'Paul',
        'Max',
        'Pierce',
        'SEC',
        'Ethereum',
        'charged',
      ],
      sentiment: {
        class: 'negative',
        polarity: -0.1,
        subjectivity: 0.6,
      },
      source: 'CryptoPotato',
      subject: 'Tether USD',
      text: "Tether was launched as RealCoin in July 2014 and was rebranded as Tether in November 2014. Originally based on the Bitcoin blockchain, Tether now supports Bitcoin's Omni and Liquid protocols as well as the Ethereum, TRON, EOS, Algorand, Solana, and Bitcoin Cash (SLP) blockchains",
      title: 'What Is Tether (USDT)?',
      url: 'https://cryptopotato.com/sec-charges-nba-hall-of-famer-paul-pierce-for-promoting-ethereum-max/',
      avatar: 'https://cdn.coinranking.com/mgHqwlCLj/usdt.svg',
    },
    {
      date: '2023-02-19 12:19:00',
      keywords: [
        'elderly British woman',
        'British woman lost',
        'elderly British',
        'British woman',
        'bitcoin scam',
        'stolen funds',
        'woman lost',
        'police restored',
        'British',
        'scam',
      ],
      sentiment: {
        class: 'positive',
        polarity: 0.25,
        subjectivity: 0.25,
      },
      source: 'CryptoPotato',
      subject: 'Tether USD',
      text: 'An elderly British woman lost more than $200,000 in a bitcoin scam, but the police restored some of the stolen funds.',
      title: 'How This Woman Lost Over $200K in a Crypto Romance Scam',
      url: 'https://cryptopotato.com/how-this-woman-lost-over-200k-in-a-crypto-romance-scam/',
      avatar: 'https://cdn.coinranking.com/mgHqwlCLj/usdt.svg',
    },
    {
      date: '2023-02-19 23:14:40',
      keywords: [
        'positive feedback loop',
        'feedback loop due',
        'creating a positive',
        'network effect',
        'positive feedback',
        'feedback loop',
        'loop due',
        'Crypto',
        'users',
        'creating',
      ],
      sentiment: {
        class: 'positive',
        polarity: 0.2,
        subjectivity: 0.47,
      },
      source: 'CoinTelegraph',
      subject: 'Tether USD',
      text: 'Crypto’s value increases with more users, creating a positive feedback loop due to the network effect.',
      title: 'What is the network effect?',
      url: 'https://cointelegraph.com/news/what-is-the-network-effect',
      avatar: 'https://cdn.coinranking.com/mgHqwlCLj/usdt.svg',
    },
  ],
};

export { bitcoin, ethereum, tetherUSD };
